version: '3.4'

## These items are either good reasonable defaults, or common enough that we don't want to repeat them.
## They can be overridden in the services after the 'import'.
x-app: &default-app
  # Need host user so don't run into permissions issues.
  user: "${JD_UID}:${JD_GID}"
  restart: always
  stop_grace_period: "3s"
  extra_hosts:
    - "${SITE_NAME}:host-gateway"
  healthcheck:
    interval: 1m
    timeout: 10s
    retries: 3
    start_period: 10s

x-default-env: &default-env
  AWS_ACCESS_KEY_ID: AWS_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET
  AWS_STORAGE_BUCKET_NAME: 'joedo'
  AWS_S3_REGION_NAME: 'us-east-1'
  AWS_S3_ENDPOINT_URL: 'http://${SITE_NAME}:9000/'
  DJANGO_SECRET_KEY: your_secret_key
  DJANGO_DEBUG: "True"
  MINIO_ROOT_USER: AWS_ID
  MINIO_ROOT_PASSWORD: AWS_SECRET
  POSTGRES_DB: joedo
  POSTGRES_HOST: postgis
  POSTGRES_PASSWORD: jd_password
  POSTGRES_USER: jd_user

x-cloud-app: &cloud-app
  networks:
    - cloud
x-client-app: &client-app
  networks:
    - client

services:
  postgis:
    image: postgis/postgis:latest
    environment:
      <<: *default-env
    volumes:
      - "postgis:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "joedo" ]
      interval: 30s
      timeout: 60s
      retries: 5

  api:
    <<: [ *default-app, *cloud-app ]
    image: joedo-api:latest
    build:
      dockerfile: api.Dockerfile
      context: .
    command: "gunicorn joedo.wsgi:application -w 4 -b 0.0.0.0:8000 --no-sendfile --reload"
    ports:
      - "8000:8000"
    volumes:
      - './:/app/.'
    working_dir: '/app'
    links:
      - minio
    depends_on:
      - postgis
    environment:
      <<: *default-env
    healthcheck:
      test: [ "CMD-SHELL", "curl", "http://localhost:8000" ]
      interval: 10s
      timeout: 20s
      retries: 5

  ui:
    <<: [ *default-app, *client-app ]
    image: joedo-ui:latest
    build:
      dockerfile: ui.Dockerfile
      context: .
    ports:
      - "5173:5173"
    command:
      - /home/node/app/node_modules/vite/bin/vite.js
    volumes:
      - './ui:/home/node/app/ui' # Don't copy whole directory, so we don't overwrite node_modules.
      - './:/home/node/app/' # Use this one instead if you want to use local node modules without rebuilding over and over.
    working_dir: '/home/node/app'
    depends_on:
      - api
    healthcheck:
      test: [ "CMD-SHELL", "curl", "http://localhost:5173" ]
      interval: 10s
      timeout: 20s
      retries: 5

  minio:
    <<: *cloud-app
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - "minio_data:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      <<: *default-env

volumes:
  minio_data:
  postgis:

networks:
  client:
  cloud:
